name: Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Donner les permissions aux scripts Cucumber
        run: chmod +x node_modules/.bin/cucumber-js

      - name: Exécuter les tests Cucumber
        run: npm run test:bdd

      - name: Sauvegarder le rapport Cucumber
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: cucumber-report.json
