name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Ajouter les permissions Playwright
        run: chmod +x node_modules/.bin/playwright

      - name: Installer Playwright et les navigateurs
        run: npx playwright install --with-deps

      - name: Exécuter les tests Playwright (Headless)
        run: CI=true npm run test:e2e

      - name: Sauvegarder les résultats des tests
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: test-results/
